baseURL = 'https://ryo9663.github.io/mypage/'
languageCode = 'ja-jp'
title = 'Mypage'
theme = "ananke"
slug = "1st-year-review"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[server]

 port = 2182546060396
